import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";


export const metadata: Metadata = {
  title: "Next.js Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto bg-slate-700 text-slate-300">
        <Header/>
          {children}
        <footer>フッター</footer>
        </body>
    </html>
  );
}
